### ISSUE TITLE
Error while running the model

### ISSUE THREAD

**Issue by Prarthana25** [yukioichida/semantic-neural-network#1]
I get the below error when I run the run_model.py:-

AttributeError: 'ProcessInputData' object has no attribute 'prepare_data'

Can you please help me with this?

**Comment by yukioichida** [comment]
Hi @Prarthana25 

Sorry for this problem, this repository contains deprecated files and lack of support (this is a 2017 work).
I created a branch 1.0.1 to put the corrections, can you check it?
If you approve, I will merge to master. Also, feel free to create new issues if needed.

**Comment by yukioichida** [comment]
Hi @Prarthana25 

I will close this issue. The solution are commited in the branch 1.0.1.
If the problem persists or if you have other problems, please open another issue.

--
Alexandre Yukio Ichida

**Comment by geetanandsagar** [comment]
sir can you please give a detailed information about the codes you provided. Please contact me asap
